name: Bash to One-Liner Git Config

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert_bash_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Convert Bash Scripts to One-Liners and Create Separate Files
        run: |
          mkdir -p oneline-configs
          
          # Inline bash-to-oneline logic
          convert_to_oneline() {
            content=$(cat "$1")
            escaped_content=$(echo "$content" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | sed 's/\$/\\\$/g')
            command_name=$(basename "$1" .sh)
            echo "git config --global alias.${command_name} '!sh -c \"$escaped_content\"'"
          }

          # Loop through each bash script and generate one-liner configs
          for script in $(find . -name "*.sh"); do
            convert_to_oneline "$script" > "oneline-configs/$(basename "$script" .sh).txt"
          done
        shell: bash

      # Debug step to list the contents of oneline-configs
      - name: List oneline-configs directory
        run: ls -al oneline-configs

      - name: Upload One-Liner Commands as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: git-one-liners
          path: oneline-configs/
