name: Bash to One-Liner Git Config

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert_bash_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Convert Bash Scripts to One-Liners and Create Separate Files
        run: |
          mkdir -p oneline-configs
          
          # Inline bash-to-oneline logic
          convert_to_oneline() {
            content=$(cat "$1")
            escaped_content=$(echo "$content" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | sed 's/\$/\\\$/g')
            command_name=$(basename "$1" .sh)
            echo "git config --global alias.${command_name} '!sh -c \"$escaped_content\"'"
          }

          # Loop through each bash script and generate one-liner configs
          for script in $(find . -name "*.sh"); do
            convert_to_oneline "$script" > "oneline-configs/$(basename "$script" .sh).txt"
          done
        shell: bash

      - name: Commit and Push One-Liner Configs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -f oneline-configs/*.txt
          git commit -m "Add updated one-liner git commands"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
